using SyncedHealth.Center.Platform.AuditCompliance.Domain.Model.Aggregates;
using SyncedHealth.Center.Platform.Shared.Domain.Repositories;

namespace SyncedHealth.Center.Platform.AuditCompliance.Domain.Repositories;

/// <summary>
/// Repository contract for audit log persistence operations.
/// </summary>
public interface IAuditLogRepository : IBaseRepository<AuditLog>
{
    /// <summary>
    /// Finds audit logs by organization identifier.
    /// </summary>
    /// <param name="organizationId">The organization identifier.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The audit logs related to the organization.</returns>
    Task<IEnumerable<AuditLog>> FindByOrganizationIdAsync(int organizationId, CancellationToken cancellationToken);

    /// <summary>
    /// Finds audit logs by actor user identifier.
    /// </summary>
    /// <param name="actorUserId">The actor user identifier.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The audit logs generated by the actor user.</returns>
    Task<IEnumerable<AuditLog>> FindByActorUserIdAsync(int actorUserId, CancellationToken cancellationToken);
}