namespace SyncedHealth.Center.Platform.AuditCompliance.Domain.Model.Queries;

/// <summary>
/// Query used to request audit logs generated by a specific actor user.
/// </summary>
public record GetAuditLogsByActorUserIdQuery(int ActorUserId);