// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncedHealth.Center.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace SyncedHealth.Center.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704221202_RemoveSeedPlansAndAddFakeDataV2")]
    partial class RemoveSeedPlansAndAddFakeDataV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SyncedHealth.Center.Platform.AuditCompliance.Domain.Model.Aggregates.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_audit_logs");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ClinicalRiskAssessment.Domain.Model.Aggregates.ClinicalAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("message");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_clinical_alerts");

                    b.ToTable("clinical_alerts");
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ClinicalRiskAssessment.Domain.Model.Aggregates.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("FatigueLevel")
                        .HasColumnType("int")
                        .HasColumnName("fatigue_level");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int")
                        .HasColumnName("heart_rate");

                    b.Property<int>("Hrv")
                        .HasColumnType("int")
                        .HasColumnName("hrv");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("risk_level");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_risk_assessments");

                    b.ToTable("risk_assessments");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            FatigueLevel = 85,
                            HeartRate = 120,
                            Hrv = 20,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 4, 22, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(4493), new TimeSpan(0, 0, 0, 0, 0)),
                            OrganizationId = 101,
                            RiskLevel = "HIGH",
                            UserId = 103
                        },
                        new
                        {
                            Id = 102,
                            FatigueLevel = 20,
                            HeartRate = 70,
                            Hrv = 60,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 4, 22, 12, 1, 562, DateTimeKind.Unspecified).AddTicks(4429), new TimeSpan(0, 0, 0, 0, 0)),
                            OrganizationId = 101,
                            RiskLevel = "LOW",
                            UserId = 104
                        },
                        new
                        {
                            Id = 203,
                            FatigueLevel = 45,
                            HeartRate = 95,
                            Hrv = 40,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 4, 22, 12, 1, 562, DateTimeKind.Unspecified).AddTicks(4435), new TimeSpan(0, 0, 0, 0, 0)),
                            OrganizationId = 101,
                            RiskLevel = "MEDIUM",
                            UserId = 205
                        },
                        new
                        {
                            Id = 204,
                            FatigueLevel = 10,
                            HeartRate = 65,
                            Hrv = 70,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 4, 22, 12, 1, 562, DateTimeKind.Unspecified).AddTicks(4436), new TimeSpan(0, 0, 0, 0, 0)),
                            OrganizationId = 101,
                            RiskLevel = "LOW",
                            UserId = 206
                        });
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ClinicalRiskAssessment.Domain.Model.Aggregates.VitalSignAnomaly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("detected_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("message");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Threshold")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("threshold");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_vital_sign_anomalies");

                    b.ToTable("vital_sign_anomalies");
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ClinicalRiskAssessment.Domain.Model.Aggregates.VitalSignReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("CortisolLevel")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cortisol_level");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("FatigueLevel")
                        .HasColumnType("int")
                        .HasColumnName("fatigue_level");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int")
                        .HasColumnName("heart_rate");

                    b.Property<int>("Hrv")
                        .HasColumnType("int")
                        .HasColumnName("hrv");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SensorStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("sensor_status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_vital_sign_readings");

                    b.ToTable("vital_sign_readings");
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.Iam.Domain.Model.Aggregates.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("email");

                    b.Property<string>("EmailError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("email_error");

                    b.Property<string>("EmailStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email_status");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("ResendEmailId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("resend_email_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_invitations");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_invitations_token");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.Iam.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("activated_at");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("registration_status");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ruc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_organizations_email");

                    b.HasIndex("Ruc")
                        .IsUnique()
                        .HasDatabaseName("i_x_organizations_ruc");

                    b.ToTable("organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "Av. Principal 123",
                            Email = "admin101@hospitalcentral.com",
                            Name = "Hospital Central CortiSense",
                            Phone = "555-0101",
                            RegistrationStatus = "COMPLETED",
                            Ruc = "1012345678901",
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("last_name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("registration_status");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("specialty_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WorkAreaId")
                        .HasColumnType("int")
                        .HasColumnName("work_area_id");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Email = "admin101@hospitalcentral.com",
                            FirstName = "Admin",
                            LastName = "User",
                            OrganizationId = 101,
                            PasswordHash = "dummyhash",
                            RegistrationStatus = "COMPLETED",
                            Role = "Admin",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = 102,
                            Email = "supervisor101@hospitalcentral.com",
                            FirstName = "Carlos",
                            LastName = "Supervisor",
                            OrganizationId = 101,
                            PasswordHash = "dummyhash",
                            RegistrationStatus = "COMPLETED",
                            Role = "Clinical Supervisor",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = 103,
                            Email = "lgomez101@hospitalcentral.com",
                            FirstName = "Laura",
                            LastName = "Gomez",
                            OrganizationId = 101,
                            PasswordHash = "dummyhash",
                            RegistrationStatus = "COMPLETED",
                            Role = "Medical Staff",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = 104,
                            Email = "jperez101@hospitalcentral.com",
                            FirstName = "Juan",
                            LastName = "Perez",
                            OrganizationId = 101,
                            PasswordHash = "dummyhash",
                            RegistrationStatus = "COMPLETED",
                            Role = "Medical Staff",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = 205,
                            Email = "atorres101@hospitalcentral.com",
                            FirstName = "Ana",
                            LastName = "Torres",
                            OrganizationId = 101,
                            PasswordHash = "dummyhash",
                            RegistrationStatus = "COMPLETED",
                            Role = "Medical Staff",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = 206,
                            Email = "lramirez101@hospitalcentral.com",
                            FirstName = "Luis",
                            LastName = "Ramirez",
                            OrganizationId = 101,
                            PasswordHash = "dummyhash",
                            RegistrationStatus = "COMPLETED",
                            Role = "Medical Staff",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = 207,
                            Email = "mlopez101@hospitalcentral.com",
                            FirstName = "Maria",
                            LastName = "Lopez",
                            OrganizationId = 101,
                            PasswordHash = "dummyhash",
                            RegistrationStatus = "COMPLETED",
                            Role = "Clinical Supervisor",
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ShiftCoordination.Domain.Model.Aggregates.CareTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkAreaId")
                        .HasColumnType("int")
                        .HasColumnName("work_area_id");

                    b.HasKey("Id")
                        .HasName("p_k_care_teams");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_care_teams_organization_id");

                    b.HasIndex("SupervisorId")
                        .HasDatabaseName("i_x_care_teams_supervisor_id");

                    b.HasIndex("WorkAreaId")
                        .HasDatabaseName("i_x_care_teams_work_area_id");

                    b.ToTable("care_teams", (string)null);
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ShiftCoordination.Domain.Model.Aggregates.ShiftRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CheckInAt")
                        .HasColumnType("datetime")
                        .HasColumnName("check_in_at");

                    b.Property<DateTimeOffset?>("CheckOutAt")
                        .HasColumnType("datetime")
                        .HasColumnName("check_out_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ScheduledEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_end");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkAreaId")
                        .HasColumnType("int")
                        .HasColumnName("work_area_id");

                    b.HasKey("Id")
                        .HasName("p_k_shift_records");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_shift_records_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_shift_records_user_id");

                    b.HasIndex("WorkAreaId")
                        .HasDatabaseName("i_x_shift_records_work_area_id");

                    b.ToTable("shift_records", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            OrganizationId = 101,
                            ScheduledEnd = new DateTimeOffset(new DateTime(2026, 7, 6, 6, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(1750), new TimeSpan(0, 0, 0, 0, 0)),
                            ScheduledStart = new DateTimeOffset(new DateTime(2026, 7, 5, 22, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(1599), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "SCHEDULED",
                            Type = "DAY",
                            UserId = 103,
                            WorkAreaId = 2
                        },
                        new
                        {
                            Id = 102,
                            OrganizationId = 101,
                            ScheduledEnd = new DateTimeOffset(new DateTime(2026, 7, 7, 2, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(2753), new TimeSpan(0, 0, 0, 0, 0)),
                            ScheduledStart = new DateTimeOffset(new DateTime(2026, 7, 6, 18, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(2750), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "SCHEDULED",
                            Type = "NIGHT",
                            UserId = 104,
                            WorkAreaId = 1
                        },
                        new
                        {
                            Id = 103,
                            CheckInAt = new DateTimeOffset(new DateTime(2026, 7, 4, 12, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(2756), new TimeSpan(0, 0, 0, 0, 0)),
                            OrganizationId = 101,
                            ScheduledEnd = new DateTimeOffset(new DateTime(2026, 7, 5, 0, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(2755), new TimeSpan(0, 0, 0, 0, 0)),
                            ScheduledStart = new DateTimeOffset(new DateTime(2026, 7, 4, 12, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(2754), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "IN_PROGRESS",
                            Type = "EMERGENCY",
                            UserId = 103,
                            WorkAreaId = 3
                        },
                        new
                        {
                            Id = 204,
                            CheckInAt = new DateTimeOffset(new DateTime(2026, 7, 3, 22, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(3546), new TimeSpan(0, 0, 0, 0, 0)),
                            CheckOutAt = new DateTimeOffset(new DateTime(2026, 7, 4, 6, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(3547), new TimeSpan(0, 0, 0, 0, 0)),
                            OrganizationId = 101,
                            ScheduledEnd = new DateTimeOffset(new DateTime(2026, 7, 4, 6, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(3545), new TimeSpan(0, 0, 0, 0, 0)),
                            ScheduledStart = new DateTimeOffset(new DateTime(2026, 7, 3, 22, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(3544), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "COMPLETED",
                            Type = "DAY",
                            UserId = 205,
                            WorkAreaId = 2
                        },
                        new
                        {
                            Id = 205,
                            OrganizationId = 101,
                            ScheduledEnd = new DateTimeOffset(new DateTime(2026, 7, 7, 6, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(4365), new TimeSpan(0, 0, 0, 0, 0)),
                            ScheduledStart = new DateTimeOffset(new DateTime(2026, 7, 6, 22, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(4364), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "SCHEDULED",
                            Type = "DAY",
                            UserId = 206,
                            WorkAreaId = 1
                        });
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ShiftCoordination.Domain.Model.Aggregates.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_specialties");

                    b.HasIndex("Name")
                        .HasDatabaseName("i_x_specialties_name");

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ShiftCoordination.Domain.Model.Aggregates.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_team_members");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_team_members_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_team_members_user_id");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_team_members_team_id_user_id");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.ShiftCoordination.Domain.Model.Aggregates.WorkArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_work_areas");

                    b.ToTable("work_areas", (string)null);
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.StaffRecovery.Domain.Model.Aggregates.RecoveryPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("MedicalStaffId")
                        .HasColumnType("int")
                        .HasColumnName("medical_staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("SuggestedRestDays")
                        .HasColumnType("int")
                        .HasColumnName("suggested_rest_days");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_recovery_plans");

                    b.HasIndex("MedicalStaffId")
                        .HasDatabaseName("i_x_recovery_plans_medical_staff_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_recovery_plans_status");

                    b.HasIndex("SuggestedRestDays")
                        .HasDatabaseName("i_x_recovery_plans_suggested_rest_days");

                    b.ToTable("recovery_plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "Alta Fatiga",
                            MedicalStaffId = 103,
                            Status = "PENDING",
                            SuggestedRestDays = 1
                        },
                        new
                        {
                            Id = 202,
                            Description = "Fatiga media detectada",
                            MedicalStaffId = 205,
                            Status = "COMPLETED",
                            SuggestedRestDays = 1
                        });
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.Subscription.Domain.Model.Aggregates.CheckoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("int")
                        .HasColumnName("administrator_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("failed_at");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("plan_code");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("stripe_session_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<string>("StripeUrl")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("stripe_url");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_checkout_sessions");

                    b.ToTable("checkout_sessions", (string)null);
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.Subscription.Domain.Model.Aggregates.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("billing_period");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency");

                    b.Property<int>("DataHistoryDays")
                        .HasColumnType("int")
                        .HasColumnName("data_history_days");

                    b.Property<string>("DisabledModules")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("disabled_modules");

                    b.Property<string>("EnabledModules")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("enabled_modules");

                    b.Property<string>("FeatureKeys")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("feature_keys");

                    b.Property<int?>("MaxDoctors")
                        .HasColumnType("int")
                        .HasColumnName("max_doctors");

                    b.Property<int>("MaxSupervisors")
                        .HasColumnType("int")
                        .HasColumnName("max_supervisors");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("int")
                        .HasColumnName("max_teams");

                    b.Property<int>("MaxWorkAreas")
                        .HasColumnType("int")
                        .HasColumnName("max_work_areas");

                    b.Property<int>("MonthlyInvitations")
                        .HasColumnType("int")
                        .HasColumnName("monthly_invitations");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<bool>("Recommended")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("recommended");

                    b.Property<string>("SupportLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("support_level");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_plans");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("SyncedHealth.Center.Platform.Subscription.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.ToTable("subscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            OrganizationId = 101,
                            PlanId = 3,
                            StartedAt = new DateTimeOffset(new DateTime(2026, 7, 4, 22, 12, 1, 561, DateTimeKind.Unspecified).AddTicks(401), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
