using Microsoft.AspNetCore.Mvc;
using SyncedHealth.Center.Platform.AuditCompliance.Application.CommandServices;
using SyncedHealth.Center.Platform.AuditCompliance.Application.QueryServices;
using SyncedHealth.Center.Platform.AuditCompliance.Domain.Model.Queries;
using SyncedHealth.Center.Platform.AuditCompliance.Interfaces.Rest.Resources;
using SyncedHealth.Center.Platform.AuditCompliance.Interfaces.Rest.Transform;

namespace SyncedHealth.Center.Platform.AuditCompliance.Interfaces.Rest.Controllers;

/// <summary>
/// REST controller for audit log operations.
/// </summary>
[ApiController]
[Route("api/v1/audit-logs")]
public class AuditLogsController(
    IAuditLogCommandService auditLogCommandService,
    IAuditLogQueryService auditLogQueryService) : ControllerBase
{
    /// <summary>
    /// Gets all audit logs.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The audit logs.</returns>
    [HttpGet]
    public async Task<IActionResult> GetAllAuditLogs(CancellationToken cancellationToken)
    {
        var query = new GetAllAuditLogsQuery();
        var auditLogs = await auditLogQueryService.Handle(query, cancellationToken);

        var resources = auditLogs
            .Select(AuditLogResourceFromEntityAssembler.ToResourceFromEntity);

        return Ok(resources);
    }

    /// <summary>
    /// Gets an audit log by identifier.
    /// </summary>
    /// <param name="auditLogId">The audit log identifier.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The audit log if found.</returns>
    [HttpGet("{auditLogId:int}")]
    public async Task<IActionResult> GetAuditLogById(
        int auditLogId,
        CancellationToken cancellationToken)
    {
        var query = new GetAuditLogByIdQuery(auditLogId);
        var auditLog = await auditLogQueryService.Handle(query, cancellationToken);

        if (auditLog is null)
            return NotFound();

        var resource = AuditLogResourceFromEntityAssembler.ToResourceFromEntity(auditLog);

        return Ok(resource);
    }

    /// <summary>
    /// Gets audit logs by organization identifier.
    /// </summary>
    /// <param name="organizationId">The organization identifier.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The audit logs related to the organization.</returns>
    [HttpGet("organizations/{organizationId:int}")]
    public async Task<IActionResult> GetAuditLogsByOrganizationId(
        int organizationId,
        CancellationToken cancellationToken)
    {
        var query = new GetAuditLogsByOrganizationIdQuery(organizationId);
        var auditLogs = await auditLogQueryService.Handle(query, cancellationToken);

        var resources = auditLogs
            .Select(AuditLogResourceFromEntityAssembler.ToResourceFromEntity);

        return Ok(resources);
    }

    /// <summary>
    /// Gets audit logs by actor user identifier.
    /// </summary>
    /// <param name="actorUserId">The actor user identifier.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The audit logs generated by the actor user.</returns>
    [HttpGet("actors/{actorUserId:int}")]
    public async Task<IActionResult> GetAuditLogsByActorUserId(
        int actorUserId,
        CancellationToken cancellationToken)
    {
        var query = new GetAuditLogsByActorUserIdQuery(actorUserId);
        var auditLogs = await auditLogQueryService.Handle(query, cancellationToken);

        var resources = auditLogs
            .Select(AuditLogResourceFromEntityAssembler.ToResourceFromEntity);

        return Ok(resources);
    }

    /// <summary>
    /// Creates an audit log.
    /// </summary>
    /// <param name="resource">The resource containing the audit log data.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>The created audit log.</returns>
    [HttpPost]
    public async Task<IActionResult> CreateAuditLog(
        [FromBody] CreateAuditLogResource resource,
        CancellationToken cancellationToken)
    {
        var command = CreateAuditLogCommandFromResourceAssembler.ToCommandFromResource(resource);
        var result = await auditLogCommandService.Handle(command, cancellationToken);

        if (result.IsFailure)
            return BadRequest(result.Message);

        var auditLogResource = AuditLogResourceFromEntityAssembler.ToResourceFromEntity(result.Value!);

        return CreatedAtAction(
            nameof(GetAuditLogById),
            new { auditLogId = auditLogResource.Id },
            auditLogResource);
    }
}